CARGO ?= cargo

.PHONY: all build build_client build_daemon build_linux build_macos build_all test check clean gen_proto download_deps help

all: build

build:
	$(CARGO) build --release
	cp target/release/sshtm ./sshtm
	cp target/release/sshtmd ./sshtmd

build_client: build
build_daemon: build

build_linux:
	$(CARGO) build --release --target x86_64-unknown-linux-gnu
	cp target/x86_64-unknown-linux-gnu/release/sshtm sshtm-linux-amd64
	cp target/x86_64-unknown-linux-gnu/release/sshtmd sshtmd-linux-amd64

build_macos:
	$(CARGO) build --release --target x86_64-apple-darwin
	cp target/x86_64-apple-darwin/release/sshtm sshtm-darwin-amd64
	cp target/x86_64-apple-darwin/release/sshtmd sshtmd-darwin-amd64
	$(CARGO) build --release --target aarch64-apple-darwin
	cp target/aarch64-apple-darwin/release/sshtm sshtm-darwin-arm64
	cp target/aarch64-apple-darwin/release/sshtmd sshtmd-darwin-arm64

build_all: build_linux build_macos

test:
	$(CARGO) test

check:
	$(CARGO) fmt --check
	$(CARGO) clippy --workspace --all-targets -- -D warnings
	$(CARGO) test

# Protobuf code is generated by build.rs as part of every Cargo build.
gen_proto:
	$(CARGO) build

download_deps:
	$(CARGO) fetch

clean:
	$(CARGO) clean
	rm -f sshtm sshtmd sshtm-* sshtmd-*

help:
	@echo "make build       Build release CLI and daemon"
	@echo "make test        Run Rust tests"
	@echo "make check       Run formatting, lint, and tests"
	@echo "make gen_proto   Generate protobuf bindings through Cargo"
	@echo "make build_all   Cross-build supported release targets"
